use_frameworks!

platform :ios, '13.0'

target 'JCBaseService_Example' do
  pod 'JCBaseService', :path => '../'
  pod 'AModule', :path => '../Modules/AModule'
  pod 'BModule', :path => '../Modules/BModule'
  pod 'CModule', :path => '../Modules/CModule'
  pod 'SnapKit'
  pod 'Kingfisher'
  pod 'SwiftLint'
  pod 'SwiftGen'
end
