use_frameworks!

platform :ios, '13.0'

target 'JCProject' do
  pod 'JCBaseService', :path => '../'
  pod 'AModule', :path => '../Modules/AModule'
  pod 'BModule', :path => '../Modules/BModule'
  pod 'CModule', :path => '../Modules/CModule'
  pod 'SnapKit'
  pod 'Kingfisher'
  pod "ESTabBarController-swift"
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
